swagger: '2.0'
info:
  description: This API can be used to manage a list of contacts.
  version: 1.0.0
  title: Contact API
  termsOfService: 'http://localhost/terms/'
  contact:
    email: apiteam@localhost
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
host: localhost
basePath: /v1
schemes:
  - http
paths:
  /contacts:
    post:
      tags:
        - contacts
      summary: Add a new contact.
      description: Adds a contact to the list of contacts.
      operationId: addContact
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: Contact object to be added to the contact list.
          required: true
          schema:
            type: object
            properties:
              firstName:
                type: string
                example: Stan
              lastName:
                type: string
                example: Lee
              company:
                type: string
                example: Marvel
              email:
                type: string
                example: stan.lee@marvel.com
              phone:
                type: string
                example: 555AVENGERS
      responses:
        '201':
          description: Contact created.
          schema:
            $ref: '#/definitions/contact'
        '400':
          description: Invalid contact data.
        '500':
          description: Internal server error.
    put:
      tags:
        - contacts
      summary: Update a contact.
      description: >-
        Updates a contact with the data provided. Any fields not supplied will
        be nulled.
      operationId: updateContact
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: Contact object to be changed.
          required: true
          schema:
            $ref: '#/definitions/'#/definitions/contact'ontact'
      responses:
        '400':
          description: Invalid contact data.
        '404':
          description: Contact not found.
        '500':
          description: Internal server error.
    get:
      tags:
        - contacts
      summary: Finds contact by their first name.
      description: >-
        This method will return all contacts that match the first name supplied
        in the querystring parameter. Partial matches will also be returned, and
        so searching for "paul" will return contacts with first names of
        "paula", "paul", and "jean-paul".
      operationId: findContactByFirstName
      produces:
        - application/json
      parameters:
        - name: firstName
          in: query
          description: >-
            The contact's first name to be used as a filter when returning
            contacts.
          required: true
          type: string
      responses:
        '200':
          description: Successful HAL HATEOS response of 0 or more contacts.
          schema:
            type: array
            items:
              $ref: '#/definitions/contacts'
        '400':
          description: The firstName was not supplied or an empty value was supplied.
        '500':
          description: Internal server error.
  '/contacts/{contactId}':
    get:
      tags:
        - contacts
      summary: Find a single Contact by their contactId.
      description: This operation will always return a single contact.
      operationId: findContactByContactId
      produces:
        - application/json
      parameters:
        - name: contactId
          in: path
          description: The contactId of the Contact to be returned.
          required: true
          type: string
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/contact'
        '404':
          description: Contact not found.
        '500':
          description: Internal server error.
    delete:
      tags:
        - contacts
      summary: Deletes a contact with the supplied contactId.
      description: This operation will delete a single contact.
      operationId: deleteContactByContactId
      produces:
        - application/json
      parameters:
        - name: contactId
          in: path
          description: The contactId of the Contact to be deleted.
          required: true
          type: string
      responses:
        '200':
          description: Contact deleted.
        '404':
          description: Contact not found.
        '500':
          description: Internal server error.
definitions:
  contact:
    type: object
    required:
      - contactId
      - firstName
      - lastName
      - company
      - phone
      - email
    properties:
      contactId:
        type: string
        description: A GUID that represents this contact uniquely.
        example: a727c7b1-79a4-4629-8a84-3234931ffcef
      firstName:
        type: string
        description: The contact's first name.
        example: Stan
      lastName:
        type: string
        description: The contact's last name or surname.
        example: Lee
      company:
        type: string
        description: The name of the company that the contact represents.
        example: Marvel
      phone:
        type: string
        description: The contact's primary telephone number.
        example: 555AVENGERS
      email:
        type: string
        description: The contact's email address.
        example: stan.lee@marvel.com
  contacts:
    type: 'object'
    properties:
      _embedded:
        type: 'object'
        properties:
          contacts:
            type: 'array'
            items:
              $ref: '#/definitions/contact'
      _links:
        type: 'object'
        properties:
          self:
            $ref: '#/definitions/links'
      page:
        type: object
        properties:
          size:
            type: integer
            description: The number of contacts per page of data returned.
            example: 5
          totalElements:
            type: integer
            description: The total number of contacts in the list.
            example: 1
          totalPages:
            type: integer
            description: The total number of pages in this list.
            example: 1
          number:
            type: integer
            description: The current page number, starting at 0.
            example: 0
  links:
    type: 'object'
    properties:
      href:
        type: string
        example: http://localhost/v1/contacts?page=0&size=5
